name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install Playwright Browsers
        # Work around for no tests found on github actions https://github.com/microsoft/playwright/issues/32503
        run: pnpm --filter <package> exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm --filter <package> exec playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
